<template>
    <main>
        <body>
            <nuxt-link to="/">Home</nuxt-link>
            <p>Lorem ipsum dolor sit amet. Et obcaecati consequatur et pariatur commodi aut aliquid laborum et pariatur voluptatem cum quia itaque ea quod aliquam? Aut amet vero hic veniam necessitatibus ad Quis minima et molestias dolor qui praesentium galisum quo sunt dolorum id cumque animi. Qui ratione ipsum est facere molestiae non quidem suscipit eos voluptatem quam ad voluptatem voluptatem et iste velit ut excepturi ipsum.
            Qui architecto omnis sit ipsa rerum cum iure veniam. Quo atque atque ex dignissimos molestiae quo quae recusandae et voluptatem repellat et provident quibusdam et esse quia hic consequatur provident? Est voluptatem quaerat et dolores galisum est ipsa animi hic vero nihil qui itaque consequuntur?
            Et sint facere aut veniam rerum rem obcaecati ipsa et voluptatem quia. Ut nisi impedit ex adipisci neque aut quia possimus. Ut eaque nemo id dolore error et earum minus est quae maxime et nobis dolorum. Ex voluptate modi in minima rerum ut praesentium sunt.</p>
            <p>Lorem ipsum dolor sit amet. Et obcaecati consequatur et pariatur commodi aut aliquid laborum et pariatur voluptatem cum quia itaque ea quod aliquam? Aut amet vero hic veniam necessitatibus ad Quis minima et molestias dolor qui praesentium galisum quo sunt dolorum id cumque animi. Qui ratione ipsum est facere molestiae non quidem suscipit eos voluptatem quam ad voluptatem voluptatem et iste velit ut excepturi ipsum.
            Qui architecto omnis sit ipsa rerum cum iure veniam. Quo atque atque ex dignissimos molestiae quo quae recusandae et voluptatem repellat et provident quibusdam et esse quia hic consequatur provident? Est voluptatem quaerat et dolores galisum est ipsa animi hic vero nihil qui itaque consequuntur?
            Et sint facere aut veniam rerum rem obcaecati ipsa et voluptatem quia. Ut nisi impedit ex adipisci neque aut quia possimus. Ut eaque nemo id dolore error et earum minus est quae maxime et nobis dolorum. Ex voluptate modi in minima rerum ut praesentium sunt.</p>
            <p>Lorem ipsum dolor sit amet. Et obcaecati consequatur et pariatur commodi aut aliquid laborum et pariatur voluptatem cum quia itaque ea quod aliquam? Aut amet vero hic veniam necessitatibus ad Quis minima et molestias dolor qui praesentium galisum quo sunt dolorum id cumque animi. Qui ratione ipsum est facere molestiae non quidem suscipit eos voluptatem quam ad voluptatem voluptatem et iste velit ut excepturi ipsum.
            Qui architecto omnis sit ipsa rerum cum iure veniam. Quo atque atque ex dignissimos molestiae quo quae recusandae et voluptatem repellat et provident quibusdam et esse quia hic consequatur provident? Est voluptatem quaerat et dolores galisum est ipsa animi hic vero nihil qui itaque consequuntur?
            Et sint facere aut veniam rerum rem obcaecati ipsa et voluptatem quia. Ut nisi impedit ex adipisci neque aut quia possimus. Ut eaque nemo id dolore error et earum minus est quae maxime et nobis dolorum. Ex voluptate modi in minima rerum ut praesentium sunt.</p>
            <p>Lorem ipsum dolor sit amet. Et obcaecati consequatur et pariatur commodi aut aliquid laborum et pariatur voluptatem cum quia itaque ea quod aliquam? Aut amet vero hic veniam necessitatibus ad Quis minima et molestias dolor qui praesentium galisum quo sunt dolorum id cumque animi. Qui ratione ipsum est facere molestiae non quidem suscipit eos voluptatem quam ad voluptatem voluptatem et iste velit ut excepturi ipsum.
            Qui architecto omnis sit ipsa rerum cum iure veniam. Quo atque atque ex dignissimos molestiae quo quae recusandae et voluptatem repellat et provident quibusdam et esse quia hic consequatur provident? Est voluptatem quaerat et dolores galisum est ipsa animi hic vero nihil qui itaque consequuntur?
            Et sint facere aut veniam rerum rem obcaecati ipsa et voluptatem quia. Ut nisi impedit ex adipisci neque aut quia possimus. Ut eaque nemo id dolore error et earum minus est quae maxime et nobis dolorum. Ex voluptate modi in minima rerum ut praesentium sunt.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <client-only>
                <about-title/>
            </client-only>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </body>
    </main>
</template>